Proyecto-Biblioteca/Models/Libros.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Proyecto_Biblioteca.Models
{
    public class Libros
    {
        //Elemtos que tandra la tabal de la base de datos
        [Key]
        public int id { get; set; }

        [Required(ErrorMessage = "El name es obligatorio")]
        [Display(Name = "Nombre")]
        public string name { get; set; }

        [Required(ErrorMessage = "El autor es obligatorio")]
        [Display(Name = "Autor")]
        public string autor { get; set; }

        [Required(ErrorMessage = "La descrpción es obligatorio")]
        [Display(Name = "Descripcion")]
        public string description { get; set; }

        [Display(Name = "Video Url")]
        public string linkVideo { get; set; }

        //[Required(ErrorMessage = "El pdf es obligatorio")]
        [Display(Name = "Url Pdf")]
        public string UrlPdf { get; set; }

        /*[Required(ErrorMessage = "Las categorias")]
        [Display(Name = "Categorias")]
        public string categories { get; set; }*/
        [NotMapped]
        [Display(Name = "Pdf Libro")]
        public IFormFile File { get; set; }
    }
}

Proyecto-Biblioteca/Controllers/LibrosController.cs
using Grpc.Core;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Proyecto_Biblioteca.Data;
using Proyecto_Biblioteca.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
namespace Proyecto_Biblioteca.Controllers
{
    public class LibrosController : Controller
    {
        private readonly ApplicationDbContext context;

        public LibrosController(ApplicationDbContext _context)
        {
            context = _context;
        }
        
        //Http Get Index
        public IActionResult Index()
        {
            IEnumerable<Libros> listaLibros = context.libros;
            return View(listaLibros);
        }
        
        //Http Get Create
        public IActionResult Create()
        {
            return View();
        }
        
        //Http Post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Libros model)
        {
            if (ModelState.IsValid)
            {
                //Creat folder if no existies
                string folderPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Docs");
                if (!Directory.Exists(folderPath))
                    Directory.CreateDirectory(folderPath);

                // Generar nombre de archivo único para evitar conflictos
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + model.File.FileName;

                // Combinar ruta con nombre de archivo único
                string filePath = Path.Combine(folderPath, uniqueFileName);

                // Guardar archivo
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    model.File.CopyTo(stream);
                }

                // Actualizar modelo con la URL del PDF
                model.UrlPdf = Path.Combine("Docs", uniqueFileName);

                // Guardar modelo en la base de datos
                context.libros.Add(model);
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.Message = "El libro no fue creado con éxito!";
            return View();
        }

        //Http Get Edit
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var libro = context.libros.Find(id);
            if (libro == null)
            {
                return NotFound();
            }
            return View(libro);
        }

        //Http Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Libros model)
        {
            if (ModelState.IsValid)
            {
                model.UrlPdf = model.UrlPdf;
                context.libros.Update(model);
                context.SaveChanges();

                //TempData["mensaje"] = "El libro se ha actualizado correctamente";
                return RedirectToAction("Index");
            }
            return View();
        }
        
        //Http Get Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var libro = context.libros.Find(id);
            if (libro == null)
            {
                return NotFound();
            }
            return View(libro);
        }
        //Http Post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteLibro(int? id)
        {
            //Obtener el libro por id
            var model = context.libros.Find(id);
            if (model == null)
            {
                return NotFound();
            }
            context.libros.Remove(model);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        //PDF
        public IActionResult PDF(int? id)
        {
            if (id == null || !id.HasValue)
            {
                return NotFound();
            }

            var libro = context.libros.Find(id);

            if (libro == null)
            {
                return NotFound();
            }

            // Usar la URL relativa del PDF
            return File(libro.UrlPdf, "application/pdf");
        }
    }
}

Proyecto-Biblioteca/Views/Libros/Create.cshtml
@model Proyecto_Biblioteca.Models.Libros
@{
    ViewData["Title"] = "Crear Libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear Nuevo Libros</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="name" class="control-label"></label>
                    <input asp-for="name" class="form-control" />
                    <span asp-validation-for="name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="autor" class="control-label"></label>
                    <input asp-for="autor" class="form-control" />
                    <span asp-validation-for="autor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="description" class="control-label"></label>
                    <input asp-for="description" class="form-control" />
                    <span asp-validation-for="description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="linkVideo" class="control-label"></label>
                    <input asp-for="linkVideo" class="form-control" />
                    <span asp-validation-for="linkVideo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="File" class="col-form-label"></label>
                    <input asp-for="File" type="file" class="form-control" required/>
                    <span asp-validation-for="File" class="text-danger"></span>
                </div>
                <div class="from-group">
                    <input type="submit" value="Crear Libro" class="btn btn-primary" />
                </div>
                @if (ViewBag.Message != null)
                {
                    <div class="alert alert-success">
                        @ViewBag.Message
                    </div>
                }
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

Proyecto-Biblioteca/Views/Libros/Delete.cshtml
@model Proyecto_Biblioteca.Models.Libros
@{
    ViewData["Title"] = "Elimirar Libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Eliminar Libro</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="DeleteLibro" enctype="multipart/form-data">
                <input type="hidden" asp-for="id" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="name" class="control-label"></label>
                    <input asp-for="name" class="form-control" disabled/>
                    <span asp-validation-for="name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="autor" class="control-label"></label>
                    <input asp-for="autor" class="form-control" disabled/>
                    <span asp-validation-for="autor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="description" class="control-label"></label>
                    <input asp-for="description" class="form-control" disabled/>
                    <span asp-validation-for="description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="linkVideo" class="control-label"></label>
                    <input asp-for="linkVideo" class="form-control" disabled/>
                    <span asp-validation-for="linkVideo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="File" class="col-form-label"></label>
                    <input asp-for="File" type="file" class="form-control" disabled/>
                    <span asp-validation-for="File" class="text-danger"></span>
                </div>
                <div class="from-group">
                    <input type="submit" value="Eliminar Libro" class="btn btn-danger" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

Proyecto-Biblioteca/Views/Libros/Edit.cshtml
@model Proyecto_Biblioteca.Models.Libros
@{
    ViewData["Title"] = "Editar Libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Editar Libro</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Edit" enctype="multipart/form-data">
                <input type="hidden" asp-for="id" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="name" class="control-label"></label>
                    <input asp-for="name" class="form-control" />
                    <span asp-validation-for="name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="autor" class="control-label"></label>
                    <input asp-for="autor" class="form-control" />
                    <span asp-validation-for="autor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="description" class="control-label"></label>
                    <input asp-for="description" class="form-control" />
                    <span asp-validation-for="description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="linkVideo" class="control-label"></label>
                    <input asp-for="linkVideo" class="form-control" />
                    <span asp-validation-for="linkVideo" class="text-danger"></span>
                </div>
                <div class="form-group" style="display: none">
                    <label asp-for="UrlPdf" class="col-form-label"></label>
                    <input asp-for="UrlPdf" class="form-control"/>
                    <span asp-validation-for="UrlPdf" class="text-danger"></span>
                </div>
                <div class="from-group">
                    <input type="submit" value="Editar Libro" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

Proyecto-Biblioteca/Views/Libros/Index.cshtml
@model IEnumerable<Proyecto_Biblioteca.Models.Libros>
@{
    ViewData["Title"] = "Lista de libros";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>@TempData["mensaje"]</strong>
        </div>
    }
    <div class="row">
        <div class="col-sm-6">
            <h3>Lista de Libros</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Libros">Agregar Libro</a>
        </div>
    </div>
    <div class="row">
        @if (Model.Count() > 0) 
        {
            <table class="table table-bordered table-striped">
                <tr>
                    <td>@Html.DisplayNameFor(m => m.id)</td>
                    <td>@Html.DisplayNameFor(m => m.name)</td>
                    <td>@Html.DisplayNameFor(m => m.autor)</td>
                    <td>@Html.DisplayNameFor(m => m.description)</td>
                    <td>@Html.DisplayNameFor(m => m.linkVideo)</td>
                    <td>@Html.DisplayNameFor(m => m.UrlPdf)</td>
                    <td>Acciones</td>
                </tr>
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.id</td>
                        <td>@item.name</td>
                        <td>@item.autor</td>
                        <td>@item.description</td>
                        <td>@item.linkVideo</td>
                        <td>@item.UrlPdf</td>
                        <td>
                            <a asp-controller="Libros" asp-action="Edit" asp-route-id="@item.id" class="btn btn-warning">Editar</a>
                            <a asp-controller="Libros" asp-action="Delete" asp-route-id="@item.id" class="btn btn-danger">Eliminar</a>
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>No existen registros</p>
        }
    </div>
</div>

Proyecto-Biblioteca/Views/Libros/PDF.cshtml
@model Proyecto_Biblioteca.Models.Libros
@{
    ViewData["Title"] = "Pdf";
}

<body>
    <div>
        <iframe src="@Url.Action("MostrarPDF", "Libros", new { id = Model.id })" width="800" height="600"></iframe>
    </div>
</body>